# Step 1 - Load clean dataset 

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("car_dataset.csv")

In [25]:
df

,car_id,name,brand,category,pricePerDay
0,1,Toyota Fortuner,Toyota,SUV,85
1,2,Honda CR-V,Honda,SUV,75
2,3,Ford Explorer,Ford,SUV,90
3,4,Hyundai Tucson,Hyundai,SUV,70
4,5,Kia Sportage,Kia,SUV,68
5,6,Nissan Patrol,Nissan,SUV,110
6,7,Mitsubishi Pajero,Mitsubishi,SUV,95
7,8,Land Rover Defender,Land Rover,SUV,150
8,9,Jeep Wrangler,Jeep,SUV,105
9,10,BMW X5,BMW,SUV,180


# Step 2 - Category Encoding


In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
encoder = OneHotEncoder()

In [12]:
category_encoding = encoder.fit_transform(df[["category"]]).toarray()

In [13]:
print(category_encoding)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


# Step 3 - Price Normalization

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scale = MinMaxScaler()

In [19]:
price_scale = scale.fit_transform(df[["pricePerDay"]])

In [20]:
print(price_scale)

[[0.01501767]
 [0.00618375]
 [0.01943463]
 [0.00176678]
 [0.        ]
 [0.03710247]
 [0.02385159]
 [0.07243816]
 [0.03268551]
 [0.09893993]
 [0.0459364 ]
 [0.06360424]
 [0.11660777]
 [0.00618375]
 [0.08568905]
 [0.09452297]
 [0.03710247]
 [0.03268551]
 [0.18727915]
 [0.16961131]
 [0.38162544]
 [0.73498233]
 [0.6024735 ]
 [0.24911661]
 [0.22261484]
 [0.204947  ]
 [0.29328622]
 [0.27561837]
 [1.        ]
 [0.91166078]
 [0.02385159]
 [0.42579505]
 [0.13427562]
 [0.1254417 ]
 [0.10777385]
 [0.05477032]
 [0.04151943]
 [0.03710247]
 [0.09452297]
 [0.33745583]
 [0.00353357]
 [0.01766784]
 [0.0459364 ]
 [0.11219081]
 [0.02650177]
 [0.82332155]
 [0.69081272]
 [0.08127208]
 [0.0680212 ]
 [0.27561837]]


# Step 4 - Feature Matrix

In [21]:
import numpy as np

In [22]:
feature_matrix = np.hstack([category_encoding , price_scale])

In [23]:
print(feature_matrix.shape)

(50, 5)


In [24]:
print(feature_matrix)

[[0.         0.         0.         1.         0.01501767]
 [0.         0.         0.         1.         0.00618375]
 [0.         0.         0.         1.         0.01943463]
 [0.         0.         0.         1.         0.00176678]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.         1.         0.03710247]
 [0.         0.         0.         1.         0.02385159]
 [0.         0.         0.         1.         0.07243816]
 [0.         0.         0.         1.         0.03268551]
 [0.         0.         0.         1.         0.09893993]
 [0.         1.         0.         0.         0.0459364 ]
 [0.         1.         0.         0.         0.06360424]
 [0.         1.         0.         0.         0.11660777]
 [0.         1.         0.         0.         0.00618375]
 [0.         1.         0.         0.         0.08568905]
 [0.         1.         0.         0.         0.09452297]
 [0.         1.         0.         0.         0.03710247]
 [0.         1

# Save all 

In [26]:
feature_df = pd.DataFrame(feature_matrix , columns=['2-Seater', 'Electric','Luxury', 'SUV', 'price_scaled'])

In [27]:
feature_df['car_id'] = df['car_id'].values
feature_df['name'] = df['name'].values

In [29]:
feature_df.to_csv("feature_matrix.csv", index=False)

In [32]:
feature_df

,2-Seater,Electric,Luxury,SUV,price_scaled,car_id,name
0,0.0,0.0,0.0,1.0,0.015018,1,Toyota Fortuner
1,0.0,0.0,0.0,1.0,0.006184,2,Honda CR-V
2,0.0,0.0,0.0,1.0,0.019435,3,Ford Explorer
3,0.0,0.0,0.0,1.0,0.001767,4,Hyundai Tucson
4,0.0,0.0,0.0,1.0,0.000000,5,Kia Sportage
5,0.0,0.0,0.0,1.0,0.037102,6,Nissan Patrol
6,0.0,0.0,0.0,1.0,0.023852,7,Mitsubishi Pajero
7,0.0,0.0,0.0,1.0,0.072438,8,Land Rover Defender
8,0.0,0.0,0.0,1.0,0.032686,9,Jeep Wrangler
9,0.0,0.0,0.0,1.0,0.098940,10,BMW X5
